name: Commerce Unbound
favicon: null
layout_spectrum: 0.25266
typography_spectrum: 0.64205
title: 'Commerce Unbound (TM) - Digital Commerce, Digital Customer Experience, Digital Marketing Industry News, Trends, and Observations from an 18-year e-commerce veteran. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ecf8f4'
    - '#2e4040'
    - '#5a817e'
    - '#007cbb'
  brandStrength: 0.851305382559076
  lightness: 0.1875
  saturation: 0.6703249600250274
  rhythmicContrast: 0.25
purpose: []
